---
# yamllint disable rule:line-length
name: docs push

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: docs-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  build-and-push-docs:
    runs-on: ubuntu-24.04
    container:
      image: shivupa/cclib-ci:py312-edge@sha256:ed389bbcd136d319f8852c9331144d1d483b7d2bf94536ae492f67df08045088
    defaults:
      run:
        shell: bash -eo pipefail -l {0}
    steps:
      - name: Installs for ssh-agent
        run: |
          apt-get update && apt-get install -y openssh-client
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          # so versioningit can figure out the version
          fetch-depth: 0
          fetch-tags: true
      - name: Allow repo access (see https://github.com/actions/checkout/issues/760)
        run: |
          git config --global --add safe.directory /__w/cclib/cclib
      - name: Prepare conda environment
        run: |
          echo "/opt/conda/envs/cclib/bin" >> "${GITHUB_PATH}"
      - name: Build docs
        run: cd doc && make default
      - name: Make a no jekyll file
        run: touch doc/sphinx/_build/html/.nojekyll
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.CCLIB_DOCS_KEY }}
        with:
          source-directory: doc/sphinx/_build/html
          destination-github-username: 'cclib'
          destination-repository-name: 'cclib.github.io'
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: master
        if: github.ref == 'refs/heads/master'
